spring:
  application:
    name: art
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    # url: jdbc:postgresql://postgres:5432/${POSTGRES_DB} # PROD
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB} # LOCAL DEV
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

garage:
  endpoint: ${GARAGE_ENDPOINT}
  access-key: ${GARAGE_ACCESS_KEY}
  secret-key: ${GARAGE_SECRET_KEY}
  region: ${GARAGE_REGION}
  bucket: ${GARAGE_BUCKET}
  public-url: ${GARAGE_PUBLIC_URL}
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${EXPIRATION_MS}
